### ISSUE TITLE
Internal mic not working

### ISSUE THREAD

**Issue by stafuz** [codepayne/linux-sound-huawei#12]
Internal mic is not working with this driver. Without the kernel patch microphone works on my notebook. It makes no sens to introduce a patch wich solves one issue and creates another. We should go ahead and make the mic working.

**Comment by codepayne** [comment]
Who's this 'we' you are talking about? I don't remember you helping me write this driver. The wiki and the emails I sent clearly explain that the internal mic doesn't work with this change. I believe that most people would like to have working sound instead of shitty internal microphone. If you are in the category of people that prefer shitty MICs don't use my driver.

**Comment by stafuz** [comment]
You are right!  If it's **YOUR** driver i will NOT use it!
