### ISSUE TITLE
Merge this driver with upstream kernel

### ISSUE THREAD

**Issue by andirsun** [codepayne/linux-sound-huawei#15]
Do you have any plans to send this kernel to the main kernel ? Also, are you accepting donations ?

**Comment by codepayne** [comment]
> Do you have any plans to send this kernel to the main kernel ? 

Yes, upstreaming the driver is planned.

> Also, are you accepting donations ?

I don't have anything set up.  Why are you asking?

**Comment by andirsun** [comment]
>I don't have anything set up. Why are you asking?

Something like github sponsors to drop a couple of bucks to help you with this plan to upstream this driver.

**Comment by bandundu** [comment]
I would be willing to give a small donation for your work because I would really appreciate having sound on my matebook but I’m too lazy to look into building the kernel myself. Upstreamed version that can get updated with pacman would be amazing.

**Comment by Alexey336** [comment]
I'd also would like to sponsor your work. After a year of using my laptop without sound from the speakers I thought I was used to it. I was wrong...

**Comment by nesterow** [comment]
I would also donate. Bluetooth speakers gonna kill me. 
I install only tested kernels from ubuntu mainline. I would build it myself on a fresh system, but now it's not an option for me.

**Comment by codepayne** [comment]
@all
Regarding the donations, thanks for the offer, but I'm not in a dire need of money so what I would suggest if you still have some funds that you want to donate, is to find an open source project that you like and donate to them.

What I do need is some help to test my newest version of the sound driver which is detailed here:
https://github.com/codepayne/pop-os-linux/wiki

If there are issues please raise an issue in that repo page.

**Comment by nesterow** [comment]
This one works for me: [codepayne/pop-os-linux](https://github.com/codepayne/pop-os-linux/wiki) 
I built it on Ubuntu 22.04.

![image](https://user-images.githubusercontent.com/48190253/224482474-1ef0091b-ca7c-4cd3-af75-f4fd608b0a29.png)

**Here are my alsa mixer settings:**

![image](https://user-images.githubusercontent.com/48190253/224481194-af41383a-5849-464a-9455-e539f05a95d6.png)

- Headphone Mux [lin-rin with Boost and PGA], otherwise a lot of static.
- When the Headphone mixer (2) is overamplified, there is a lot of static.
- By default, everything in alsamixer was muted, so I had to unmute channels manually. Not an issue, but It got me confused)

It worked for me without any additional configuration.
I didn't find any other issues, however, I didn't install this kernel on a fresh system - my laptop already had some blacklisted drivers and other settings, so I wouldn't be able to catch any actual configuration-related issues.

If anyone couldn't build it, but still wants to test it, I can share my builds (debian packages).

@codepayne Many thanks! I'll keep you posted if I find any bugs.

**Comment by yimboka** [comment]
I build in on opensuse with kernel 6.2.7 with a little modification on one patch ([PATCH] Add support for amd acp3x es83xx)
There is a problem : when I plug and unplug my headphone, the headphone in alsamixer is set to 0. The result : no sound on speaker. I have to put a value greater than 0.

Sound on headphone works, and on speaker too.

**Comment by Jeronimo1983** [comment]
https://github.com/codepayne/pop-os-linux/issues/4

**Comment by bandundu** [comment]
Are there any updates to this hitting upstream? Thanks again for the hard work

**Comment by codepayne** [comment]
> Are there any updates to this hitting upstream? Thanks again for the hard work

Yes, there are updates, the driver should be in starting with kernel version 6.7. It hasn't been pulled by Linus yet since only bug fixes are being accepted right now. But it has been pulled in by sound subsystem maintainer. 

https://lore.kernel.org/alsa-devel/169447665042.2387538.16679409837029670258.b4-ty@kernel.org/

**Comment by fdecarpentier** [comment]
Thank you for the great work. I see that v6.7 merge has started (https://www.phoronix.com/news/Linux-6.7-Big-Merge-Window), have you heard from your driver?

**Comment by codepayne** [comment]
> Thank you for the great work. I see that v6.7 merge has started (https://www.phoronix.com/news/Linux-6.7-Big-Merge-Window), have you heard from your driver?

It has been pulled by Linus: 
https://github.com/torvalds/linux/commit/54fcd9dd44b2c82a0262e29b288c2d0b36c6bba5

**Comment by fernandosang** [comment]
> > Thank you for the great work. I see that v6.7 merge has started (https://www.phoronix.com/news/Linux-6.7-Big-Merge-Window), have you heard from your driver?
> 
> It has been pulled by Linus: [torvalds/linux@54fcd9d](https://github.com/torvalds/linux/commit/54fcd9dd44b2c82a0262e29b288c2d0b36c6bba5)

Sorry, I'm pretty ignorant when it comes to kernels, but I have a Matebook 14 AMD 2020 and I've been trying to make sound work for over a year now. Can I ask, what are the implications of this? Can I expect this fix you came up with will be included in the kernel all distros come with by default in the future? Or is there anything I can do right now to make it work on, say, ElementaryOS, Ubuntu, etc.?

I would appreciate some light on this. Thank you.

**Comment by codepayne** [comment]
> ith by default in the future? Or is there anything I can do right now to make it work on, say, ElementaryOS, Ubuntu, etc.?

Yes in the future all distros should have this driver as a kernel module, so the sound should work automatically. The thing is, that it's not clear when that will happen. Debian and Ubuntu are more conservative and switch slower to new kernel versions. Gentoo, Arch move much faster.

**Comment by codepayne** [comment]
Driver is upstream.
